from pathlib import Path
import json
from docx import Document
from docx.shared import Mm, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
ROOT=Path('/Users/scottcryan/courier-emu')
OUT=ROOT/'artifacts/x2-spec-20261004'
PAYLOAD=json.loads((ROOT/'artifacts/x2-payload-mapper-20261004/verification.json').read_text())
PAIR=json.loads((ROOT/'artifacts/imodem-pair-x2-full-rate-high-power-20261002/verification.json').read_text())
PAIR_CONTROL=json.loads((ROOT/'artifacts/imodem-pair-x2-full-rate-v8-server-20261002/verification.json').read_text())
d=Document(); sec=d.sections[0]
sec.page_width=Mm(210);sec.page_height=Mm(297)
sec.top_margin=Mm(21);sec.bottom_margin=Mm(20);sec.left_margin=Mm(22);sec.right_margin=Mm(22)
for name in ['Normal','Title','Subtitle','Heading 1','Heading 2','Caption']:
 s=d.styles[name];s.font.name='Times New Roman';s.font.color.rgb=RGBColor(0,0,0)
 s.font.size=Pt(11 if name=='Normal' else 14 if name=='Heading 1' else 12 if name=='Heading 2' else 10 if name=='Caption' else 22 if name=='Title' else 12)
 s.paragraph_format.space_after=Pt(6)
 s.paragraph_format.line_spacing=1.08
 for x in s.element.xpath('.//w:rFonts'):
  for key in list(x.attrib):
   if 'theme' in key.lower():del x.attrib[key]
 for x in s.element.xpath('.//w:pBdr'):x.getparent().remove(x)
for name in ['Heading 1','Heading 2','Caption']:d.styles[name].paragraph_format.keep_with_next=True
d.styles['Title'].font.bold=True
h=sec.header.paragraphs[0];h.text='COURIER EMU     x2 firmware reconstruction     Draft 0.21';h.runs[0].font.size=Pt(9)
f=sec.footer.paragraphs[0];f.alignment=WD_ALIGN_PARAGRAPH.CENTER
f.add_run('x2 technical specification     •     4 October 2026     •     ')
field=OxmlElement('w:fldSimple');field.set(qn('w:instr'),'PAGE');f._p.append(field)
for r in f.runs:r.font.size=Pt(9)
def p(t,style=None):return d.add_paragraph(t,style)
pending_page=False
def hd(t):
 global pending_page
 pp=d.add_heading(t,1)
 if pending_page:
  pp.paragraph_format.page_break_before=True
  pp.paragraph_format.space_before=Pt(0)
 pending_page=False
def sub(t):d.add_heading(t,2)
def page():
 global pending_page
 pending_page=True
def table(cap,heads,rows,widths):
 p(cap,'Caption');t=d.add_table(rows=1,cols=len(heads));t.alignment=WD_TABLE_ALIGNMENT.CENTER;t.autofit=False
 for c,w in zip(t.columns,widths):c.width=Mm(w)
 for c,x in zip(t.rows[0].cells,heads):c.text=x
 repeat=OxmlElement('w:tblHeader');t.rows[0]._tr.get_or_add_trPr().append(repeat)
 for row in rows:
  for c,x in zip(t.add_row().cells,row):c.text=str(x)
 for n,row in enumerate(t.rows):
  trpr=row._tr.get_or_add_trPr();trpr.append(OxmlElement('w:cantSplit'))
  for c,w in zip(row.cells,widths):
   c.width=Mm(w);c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
   pr=c._tc.get_or_add_tcPr();b=OxmlElement('w:tcBorders')
   for side in ['top','left','bottom','right']:
    x=OxmlElement('w:'+side);x.set(qn('w:val'),'single');x.set(qn('w:sz'),'4');x.set(qn('w:color'),'D9D9D9');b.append(x)
   pr.append(b)
   if n==0:
    sh=OxmlElement('w:shd');sh.set(qn('w:fill'),'E7E7E7');pr.append(sh)
   margins=OxmlElement('w:tcMar')
   for side in ['top','left','bottom','right']:
    x=OxmlElement('w:'+side);x.set(qn('w:w'),'85');x.set(qn('w:type'),'dxa');margins.append(x)
   pr.append(margins)
   for pp in c.paragraphs:
    pp.paragraph_format.space_after=Pt(1);pp.paragraph_format.line_spacing=1
    for r in pp.runs:r.font.size=Pt(10);r.bold=(n==0)
 p('')
def code(t):
 for line in t.splitlines():
  pp=p(line);pp.paragraph_format.space_after=Pt(0)
  for r in pp.runs:r.font.name='Courier New';r.font.size=Pt(9)

p('x2 Modem Technical Specification','Title')
p('Negotiation downstream mapping and symmetric operation','Subtitle')
p('Draft 0.21   •   Independent firmware reconstruction   •   4 October 2026')
hd('1 Scope and operating model')
p('This document explains x2 negotiation and data mapping for asymmetric and symmetric operation. It covers the Courier 3453C analogue client, original I-modem server and later Quad mapper evidence. Clauses 12 to 14 describe symmetric operation and the successful digital pair. Clauses 15 to 17 cover the rate ladder, lower-rate mapping and scrambling. Clause 18 verifies the PCM record consumer, rate selector and later source handoff. Clauses 19 and 20 reconstruct client rate selection, position grouping and variable-length record serialization in pre-V.90 and later firmware.')
p('The client retains executable x2 setup and DSP code. The server capability exchange and sample transforms have been reconstructed. The later Quad reconstruction connects received parameters to six mapping banks and provides an execution-checked source-byte-to-codeword core with amplitude selection and sign shaping. Stock controller copies validate overlay placement. Complete peer negotiation and analogue client decoding remain open.')
p('In an asymmetric connection, the digital server supplies downstream sample codewords. The analogue client receives the resulting waveform and must recover the information represented by the chosen levels. The upstream direction uses the related V.34 machinery. In symmetric operation both endpoints are digitally attached and send and receive at the same x2 rate. A paired emulator test establishes 64000/64000 carrier and bidirectional marker delivery; the complete symmetric negotiation and data transition have not yet been reconstructed.')
p('A constellation is the set of signal levels available for carrying data. A mapper selects members from input data; the receiver performs the inverse. A level table alone does not establish framing, shaping, synchronization or payload decoding.')
hd('2 Status of the specification')
p('The numbered clauses and field tables follow the style of an ITU technical specification. This is an independent engineering draft, not an ITU-T Recommendation. Statements describe the recovered firmware profile; they are not universal requirements for all x2 equipment.')
table('Table 1 — Evidence used in this draft',['Designation','Meaning'],[('Verified','A semantic reconstruction matches original DSP instructions, or a stated behavior passes a recorded emulator call test. The qualification identifies which evidence applies.'),('Observed','Firmware instructions, constants or message construction establish a local operation without validating its complete protocol procedure.'),('Provisional','Component behavior is reproducible, but a placement assumption or protocol interpretation remains unverified.'),('Open','The available evidence does not yet establish the procedure.')],[30,136])
p('Annex A collects firmware references, memory layouts and reproduction commands. The main clauses describe connection behavior and signal parameters. Timing and interoperability requirements are stated only where the evidence supports them.')

page();hd('3 Negotiation sequence')
p('Table 2 organizes the recovered operations into a connection sequence. The individual operations are supported to different degrees; their complete ordering and transition timing have not been demonstrated in one end-to-end call.')
table('Table 2 — Recovered negotiation stages',['Stage','Purpose and observed behavior','Status'],[('Local selection','Check whether x2 is enabled and permitted by the selected mode, speed settings and line conditions. Prepare its capability announcement.','Observed'),('Capability exchange','Use the INFO0 capability structure to announce permitted asymmetry and related attributes. The server route into the outgoing capability buffer is verified.','Verified in server'),('Directional announcement','Transmit a short proprietary body naming a carrier choice and two modulation-rate indices. One index can identify the PCM direction.','Observed'),('Channel qualification','Evaluate peer parameters and a signed channel margin. Related rate machinery limits the requested rate against available capability.','Partial'),('Training and probing','Generate a repeating startup source and collect received training words and a position bitmap.','Source verified'),('Constellation preparation','Decode received choices, select candidate level sets and expand six position banks.','Components verified'),('Data operation','Map source bytes to six codewords with differential signs and disparity shaping. An ideal symbol inverse recovers the bytes; analogue client decoding and call alignment remain open.','Core verified')],[34,103,29])
sub('3 1 Local selection and fallback')
p('The client calls a distinct x2 eligibility procedure during connection setup. It excludes disabled x2 operation, unsuitable modem modes and speed or line conditions that fail the firmware gates. The neighboring V.90 selection procedure is separate. Retaining an x2 setup call establishes an active selection mechanism, but does not prove successful peer negotiation.')
p('The setup prepares a capability pattern describing directional asymmetry. Some settings can suppress that asymmetry. Equal modulation indices in a later announcement establish equal directional parameters, but do not by themselves identify x2 symmetric operation: the equal pair shown in Table 5 uses ordinary V.34 index 4. Symmetric x2 has separate role capability controls, described in clause 12. The precise transition from rejected x2 operation to an established fallback connection is still open.')
sub('3 2 What remains to connect')
p('The 3453C supervisor builds two capability words from the same base: the plain word, sent as mailbox tag 51, and the x2-edited word, sent as tag 70. The DSP stores them at separate locations. The negotiation-start routine at 0A64 reads only the plain location, forces the clock-source field to the value one and queues the result as a sixteen-bit field of the INFO0 work buffer. Nothing in the four images reads the tag 70 location. The x2 asymmetry and CME edits therefore do not reach the INFO0 field in this build, whereas the pre-V.90 server selects between its two words with a state bit. A component test varies both words and shows the queued field follows the plain word alone. Whether a deployed client announced x2 asymmetry through another route, or relied on the later V.90 exchange, is not established by this firmware.')

page();hd('4 Capability and modulation announcements')
sub('4 1 INFO0 capability fields')
p('The interpreted client capability announcement uses fields already present in the V.34 INFO0 structure. The supervisor sets the permitted asymmetry, clears the CME indication and clears the clock-source field. Table 3 states the interpreted wire field correspondence. The server capability word has a verified route into its INFO0 work buffer; actual frame emission and peer acceptance remain separate checks. In the 3453C DSP the clock-source field is set to one rather than zero before queueing; the pre-V.90 server clears it.')
table('Table 3 — Interpreted capability fields',['INFO0 bits','Parameter','Client construction'],[('21 to 23','Maximum directional symbol-rate difference','An integer from 0 to 3, selected by the two relevant S58 settings'),('24','CME indication','Cleared'),('26 to 27','Transmit clock source','Cleared')],[29,63,74])
p('With both relevant S58 options clear, the asymmetry integer is 2. Enabling the first option alone makes it 3; enabling the second alone makes it 0; enabling both makes it 1. These are numerical values, not printed bit strings that might be confused with transmission order.')
sub('4 2 Directional modulation parameters')
p('The proprietary body has seven bits. The lowest bit selects the carrier; the next three bits hold the first modulation index and the highest three hold the second. The roles of the two indices interchange with the modem role flag. Index 6 is interpreted as the PCM-direction indication; ordinary V.34 modulation indices occupy the range 0 to 5.')
table('Table 4 — Directional announcement body',['Body bits','Width','Meaning'],[('0','1','Carrier choice: 0 low, 1 high'),('1 to 3','3','First modulation index'),('4 to 6','3','Second modulation index')],[28,20,118])
table('Table 5 — Observed announcement values',['Body value','Carrier','First index','Second index'],[('4D hexadecimal','High','6','4'),('69 hexadecimal','High','4','6'),('48 hexadecimal','Low','4','4'),('49 hexadecimal','High','4','4')],[52,38,38,38])
p('The first two values announce the same asymmetric pair with its directions exchanged. The latter two name equal ordinary V.34 indices and differ only in carrier choice; they are not proof of a PCM connection in both directions. These values come from the inspected Courier announcement builders; they have not been established as a complete set of every possible x2 peer message.')

page();hd('5 Framing recognition and rate agreement')
sub('5 1 Transmitted announcement structure')
p('The recovered x2-only announcement script contains two lead-in ones, twelve bits of fill and synchronization, the seven-bit body, sixteen check bits and four closing ones. The framed portion is 39 bits; including the lead-in gives 41 emitted script bits. A lead-in is therefore not counted as part of the 39-bit frame.')
table('Table 6 — Announcement script in emission order',['Element','Bits','Interpretation'],[('Lead-in','2','Two ones before the framed portion'),('Fill and synchronization','12','Shared INFO framing sequence'),('Information body','7','Carrier and directional modulation indices'),('Check field','16','INFO CRC family'),('Closing fill','4','Four ones')],[60,20,86])
p('The local field encoder models the body least-significant bit first and the V.34 INFO CRC initialized to all ones, using the reflected form of the polynomial with terms of order 16, 12, 5 and 0. This is a working serialization model. A captured x2 frame or an executed complete serializer is still needed to validate every bit convention.')
sub('5 2 Receiver recognition')
p('A seven-bit comparison in the shared receiver was previously interpreted as recognition of the proprietary announcement. That interpretation is superseded: the same comparison exists in pre-x2 V.34 firmware and matches a window of the INFO fill and synchronization preamble. It does not identify an x2 body value.')
p('The receiver is the ordinary framed INFO receiver, armed for a seven-bit body. The Quad server arms it after its capability gate, which requires the x2 capability word to be selected, a set peer bit and a differing eleventh word bit between the peer and local capability words. The body is accepted as a frame by the standard synchronization and CRC test; the receiver does not search the raw bit stream.')
p('The parse reads the carrier bit first, then two three-bit indices in transmission order. The role flag selects which index belongs to the receiver. If that index is six the server keeps the x2 state and records the carrier choice for the other index; otherwise it clears the x2 selection and continues as ordinary V.34. The originator announcement 4D hexadecimal is therefore accepted by a server holding the answering role flag, and the answerer announcement 69 hexadecimal by the opposite flag. The symmetric values 48 and 49 hexadecimal contain no six and are not accepted as x2 markers.')
p('Executing the original parse for every body value and both role flag values reproduces this layout, with thirty-two accepted combinations. In a recorded analogue client to I-modem call the server buffer holds the originator announcement 4D hexadecimal at the position the parse reads, and the accept branch executes.')
p('Acceptance is not answered on the line. The server clears the role flag bits, sets an x2 mark, resets its receive state, retunes its receive symbol rate and carrier from the announced index and carrier bit, installs a different pair of timing callbacks and waits a fixed count of symbol periods. It then reports the index to the host. The index is the ordinary V.34 symbol rate index, with 4 meaning 3200 symbols per second. Acknowledgement, timeout and retry behavior beyond this are not established.')
sub('5 3 Channel qualification and rate limits')
p('The 3453C qualification fragment tests a peer attribute and computes a signed margin from peer parameters and a channel measurement. A positive margin enables a subsequent state choice. The physical unit of that margin and the peer identity implied by the test remain open.')
p('Related later firmware compares a host-requested maximum with the existing maximum and retains the smaller value. Its two directional rate fields exchange roles with the same role flag used by the directional announcement. It also intersects enabled rate capabilities with a symbol-rate-dependent mask and the extended-constellation capability. This is evidence of inherited V.34 rate agreement; its complete x2-specific binding remains open.')
p('Repository rate analysis supports a six-symbol downstream organization with nominal rate increments of 8,000 ÷ 6 bit/s. The new six-position mapper evidence is consistent with that organization. Consistency does not establish its alignment signal, negotiated bit allocation or exact rate-selection procedure.')

page();hd('6 Startup and receiver qualification')
sub('6 1 Repeating startup source')
p('The original server has a four-state startup source. Starting from its initialized state, it repeats the 2,010-call cycle in Table 7. Execution comparison over 4,096 consecutive source calls covers two complete cycles and part of a third.')
table('Table 7 — Verified server source cycle',['Part','Source words','Count'],[('Training prefix','Repeated hexadecimal 7E','1,747'),('Separator','Zero','7'),('Probe pairs','Ascending first word and descending second word: (0,255), (1,254), continuing to (127,128)','128 pairs'),('Restart','Return to the training prefix','Cycle repeats')],[34,102,30])
p('The pair generator advances the ascending value after selecting its return word, then emits the descending value before decrementing it. On the last pair, it restores the prefix count and returns to the first state. The reconstructed delayed-return updates match the original instructions.')
p('These are source words. The selected output path may mask their width, scramble them and reverse an octet before transmission. A source-call count does not establish elapsed time. The sample cadence and callback selected during each startup stage must be traced before specifying an on-wire duration.')
sub('6 2 Received training and position bitmap')
p('The inspected receive chain begins by qualifying repeated training values. It advances a position counter over six positions and accumulates a bitmap. Later code classifies received low-valued patterns, records words in a small report buffer and changes receive substates. The initial detector seeks seven qualifying training values before advancing.')
p('The bitmap and recorded reports are plausible inputs to channel qualification and constellation selection, but their full relationship to the outgoing probe pairs is not established. The receiver has not yet been execution compared as a complete sequence. Its report format, rejection conditions and transition deadlines remain open.')
sub('6 3 Transition to operating transforms')
p('The server sample path can select seven-bit or eight-bit source words. Transmission applies the selected mask, optional scrambling, optional octet reversal and an output write. Reception records a sample, performs the inverse reversal, applies the mask and optionally descrambles it before delivery.')
p('The tested sample transforms match the original routines with payload source and sink dispatch disabled. They establish transformation behavior, but not supervisor queue delivery or a complete data connection. A seven-bit digital bearer word must not be interpreted as the downstream analogue x2 rate without the mapper and frame allocation.')

page();hd('7 Negotiated downstream parameters')
sub('7 1 Transfer of the received record')
p('In the inspected PCM receive branch, four buffered words become the working negotiation record. The first two words supply directional parameters; the last two supply the position choices and an additional parameter. This transfer and the subsequent unpacking match the original instructions. The branch condition is part of the verified entry context. Clause 18 additionally executes reception and CRC acceptance of the four-word PCM record in a tested mode; complete acknowledgement and call-state selection remain open.')
table('Table 8 — Recovered working parameters',['Parameter','Recovered representation','Qualification'],[('Original mode','Four bits from the first working word','Used to select a scale table'),('Effective mode','Original mode, or zero when a local override is set','Used by a second parameter table'),('Independent sign count','Three bits above the position record','MD from 0 to 6; values outside this range are unverified'),('Position record','Twenty-four bits organized as six four-bit cells','Three bits of each cell select a control value')],[37,71,58])
p('The distinction between original and effective mode is observable: a local override changes the stored mode to zero, while one scale-table lookup retains the original mode. The draft therefore keeps both parameters distinct. Their exact rate names and the physical units of the scale values have not been established.')
sub('7 2 Conversion of position choices')
p('The firmware consumes the six cells from the most significant end of its working record. It ignores the upper bit of each cell and converts the lower three bits according to Table 9. Each result occupies two bits in the position-control word. Bank expansion then consumes that word from its least significant end, so its first bank corresponds to the last cell processed during unpacking. This describes working-record order; wire order remains to be established.')
table('Table 9 — Cell value to position control',['Cell value','0','1','2','3','4','5','6','7'],[('Control','0','1','2','1','0','3','0','3')],[38,16,16,16,16,16,16,16,16])
p('The firmware also counts the nonzero controls. If all six controls are zero, it substitutes a control word with the lowest position set to value 2, while retaining an active-position count of zero. This is a distinct default state. It must not be described as six ordinary zero choices or silently recounted as one active position.')
sub('7 3 Extent of the verified negotiation path')
p('Received-record transfer, unpacking and bank expansion match the original instructions for all 4,096 position-control combinations, including both values of the ignored cell bit. Those checks supply candidate sets before expansion. The original builder and its consumers also execute together for 30 seeded payload profiles, supplied with a rate index and received record. The server record receiver, rate-mask intersection and mapper handoff are now execution-checked in clause 18. Client measurement-to-record selection, training-bitmap binding and complete peer agreement remain open.')

page();hd('8 Downstream mapping organization')
sub('8 1 Six positions and two candidate sets')
p('Six two-bit controls select the candidate sets for the six positions. A size-distribution routine assigns one of two set sizes to each position: control zero chooses the high-byte size and controls 1, 2 or 3 choose the low-byte size. The count and size routines match the original instructions for all 4,096 combinations.')
table('Table 10 — Position control behavior',['Control','Candidate set','Additional expansion flag'],[('0','First candidate','Clear'),('1','Second candidate','Set'),('2','Second candidate','Clear'),('3','Second candidate','Set')],[25,75,66])
p('The expansion flag sets the stored sign bit of a working entry. Payload sign selection toggles this bit, so the flag determines the reference polarity for that candidate bank. It does not carry an additional independent payload bit.')
sub('8 2 Expansion into working banks')
p('The expansion component constructs six working banks from the two candidate tables. It consumes one control per bank, chooses the corresponding source set and copies its configured length. An odd control sets the additional flag in each copied entry. Successive banks begin 128 words apart; that spacing is a storage stride, not a requirement to use 128 levels.')
p('The expansion uses a last-index convention: a configured value of three copies four entries. The startup caller supplies the value nine, so expansion copies ten entries, whereas the constructor and level-conversion loop each prepare nine. Tests seed the additional entry explicitly. The payload amplitude selector treats the configured size as a radix and selects indices zero through size minus one. It therefore uses only nine entries for radix nine; the copied tenth entry is outside this payload selection range. Its use elsewhere remains open.')
sub('8 3 Constructor and consumer execution')
p('The original startup caller has now been executed through candidate construction, level conversion and six-bank expansion in 128 seeded contexts. It sets all six size slots to nine, preserves the selected constructor codewords in the low octets, and copies the transformed candidate entries into the banks selected by the controls. These checks cover the unmodified caller and its callees together.')
p('The second candidate table and additional entries are seeded in those contexts. The result verifies their consumption and the constructor relationship; it does not establish how both candidates are populated in an actual negotiated connection. The intermediate level converter has been executed, but its amplitude and companding interpretation has not been independently reconstructed.')
sub('8 4 Verified source placement')
p('A fresh stock controller run copied all seven overlay sources into each of the four modem RAM banks. All 28 byte comparisons matched the corrected source offsets over the complete overlay lengths. The earlier one-word discrepancy was a flat-file extraction error. The downloader does not discard a leading word. This removes the placement qualification from the component results in clauses 7 to 9.')

page();hd('9 Codeword sets and signal realization')
sub('9 1 Paired constructor tables')
p('The constructor selects one of the two nine-entry tables in Table 11 according to a local mode flag. Every value in the second table is sixteen lower than the corresponding value in the first. These are alternative constructor tables; they must not be equated automatically with the two candidates consumed by bank expansion. The corrected source placement and original startup caller both support the table contents.')
table('Table 11 — Paired constructor values',['Entry','First set','Second set'],[(i+1,a,b) for i,(a,b) in enumerate(zip(['A5','A7','AD','AF','B7','BD','C5','CF','E5'],['95','97','9D','9F','A7','AD','B5','BF','D5']))],[40,63,63])
p('All entries are hexadecimal codeword values in stored table order. The difference of sixteen is a relationship between codeword indices. It shall not be converted into a fixed amplitude ratio or assigned to a companding law until the selected law and subsequent conversion path are established.')
sub('9 2 From constellation choice to a transmitted sample')
p('The recovered preparation chain selects parameter tables, derives candidate sizes, distributes them across six positions and expands working banks. The preceding mapping block also processes six values and uses auxiliary level tables. Together these establish a concrete six-position preparation architecture, beyond an isolated list of codewords.')
p('Clauses 10 and 11 specify the recovered payload core: source scrambling and bit grouping, mixed-radix amplitude selection, differential signs, minimum-disparity shaping and output formatting. Tests execute the original frame dispatcher and sample steps repeatedly. This establishes the local six-symbol boundary; the signal that establishes that boundary between peers remains open.')
sub('9 3 Remaining connection requirements')
p('A complete connection still requires the client training measurements to be connected to its outgoing rate and constellation record, peer alignment to be traced, and the client equalizer and payload decoder to be reconstructed. The larger Quad PCM overlay supplies the payload evidence. Its record-to-rate/bank/data handoff is verified in clause 18, while complete x2 call-state selection remains open. These results shall not be assumed to describe every x2 or V.90 operating branch.')

page();hd('10 Payload framing and amplitude selection')
sub('10 1 Parameters and bit organization')
p('A data frame produces six codewords, one for each selected position bank. B specifies the number of amplitude-selection bits. MD specifies the number of independent sign bits, from zero to six. The frame consumes MD sign bits first, followed by B amplitude bits, for a total of B + MD information bits. Within each group, the first consumed bit is the least significant bit of the corresponding integer.')
table('Table 12 — Payload parameters',['Symbol','Meaning','Recovered range'],[('B','Amplitude bits consumed per six-symbol frame','19 to 37 in the rate-index table'),('MD','Independent sign bits per frame','0 to 6'),('m₀ to m₅','Number of selectable entries in each position bank','Configured separately for each position'),('X','Unsigned integer represented by the B amplitude bits','Zero through 2ᴮ minus one')],[28,101,37])
p('The remaining six minus MD signs are shaping choices. They consume no independent source bits. MD equal to six removes this sign-search freedom; MD equal to zero leaves all six signs available for shaping. The tested bank configurations cover all fifteen local rate indices with SPM 1. Index 15 supplies a verified 37-bit amplitude allocation; with MD = 6 it corresponds to 57333⅓ bit/s. Clause 16 describes its constructed bank variants.')
sub('10 2 Scrambling and source buffering')
p('Source words are scrambled before entering a circular 128-bit buffer. The recovered source routine supports word widths from one to eight bits. Continuous byte tests use eight-bit words. The modem role flag selects one of two feedback recurrences; the scrambler history continues across byte and frame boundaries. Each scrambled word enters the buffer least significant bit first.')
p('The frame reader also advances least significant bit first and wraps at the end of the buffer. The dispatcher requests more source input unless the available bit count is strictly greater than B + MD. Equality therefore triggers a refill even though the next frame itself would fit. The dispatcher checks availability for every output sample. The stream harness prefills enough bits to retain this margin after consuming a frame.')
sub('10 3 Mixed radix amplitude selection')
p('Let X₀ be X. For position i, from zero through five, divide Xᵢ by the configured bank size mᵢ. The remainder selects the entry in that position bank; the quotient becomes Xᵢ₊₁ for the next position. Position zero therefore carries the least significant mixed-radix digit. Bank sizes may differ.')
p('Equivalently, X = a₀ + m₀a₁ + m₀m₁a₂ + m₀m₁m₂a₃ + m₀m₁m₂m₃a₄ + m₀m₁m₂m₃m₄a₅, where aᵢ is the selected entry index and 0 ≤ aᵢ < mᵢ. A valid allocation requires the product of the six bank sizes to be at least 2ᴮ. Combinations representing X ≥ 2ᴮ are unused amplitude combinations for this allocation.')
p('Each selected entry supplies a reference codeword and an unsigned level index. The level index selects the magnitude used by sign shaping and linear sample monitoring. The codeword carries its own reference polarity, which the sign stage may toggle. Unique decoding requires distinct low-seven-bit reference codewords within each selected bank.')

page();hd('11 Differential signs and disparity shaping')
sub('11 1 Independent sign encoding')
p('The MD input sign bits update a continuous binary parity state. Each new parity value is the previous parity exclusive-OR the next input bit. The resulting parity values determine the independent sign toggles. This state persists between frames; resetting it at every frame would change the payload representation.')
p('When MD is less than six, positions are ranked by selected level index, with the largest index first. Equal indices are ordered by position, with the first emitted position taking precedence. The MD highest-ranked positions receive the independent sign toggles. The toggles are assigned to those positions in emission order, rather than in rank order. With MD equal to six, all positions receive them directly in emission order.')
sub('11 2 Selection of the remaining signs')
p('The firmware combines the fixed independent signs with a running disparity term, then considers every sign assignment for the remaining positions. It selects the assignment with the smallest absolute resulting disparity. At most 64 assignments are needed when all six signs are free. The level contributions in this search use the recovered sign-toggle convention; the final stored polarity also includes the reference sign already present in the bank entry.')
p('The disparity term equals eight times a signed delayed monitor value. The monitor follows emitted signed linear levels, with each level shifted right by three bits using arithmetic rounding. Its delayed state feeds the following frame’s sign decision. Reconstructing only a single isolated frame would omit this dependence.')
p('Free signs are numbered in emission order. The search examines their binary masks from the largest to zero and replaces its choice only for a strictly smaller absolute disparity. Ties therefore select the largest mask. This deterministic tie rule is part of the recovered mapping.')
sub('11 3 Codeword and sample output')
p('Each selected sign toggle changes bit seven of its reference codeword. The six resulting octets are emitted in bank order. A configured final exclusive-OR mask, either zero or hexadecimal 2A in the tested profiles, converts the stored representation to the selected output format. It applies after sign selection.')
p('The sample step also converts the selected level to signed linear form, updates the disparity monitor and energy accumulator, applies the negotiated scale, and writes a circular delay buffer. The recovered core and C reconstruction agree on these effects for the ordinary output branch. An optional alternate companding branch selected by another local override remains outside this verified scope.')
sub('11 4 Ideal decoding and continuity')
p('Given the six correctly received octets, a decoder first reverses the final format mask. For each bank it matches the low seven codeword bits to a unique reference entry, recovering the amplitude digit and the sign toggle relative to that entry. Combining the digits reconstructs X. The same level ranking identifies which signs carry information; consecutive parity values recover the MD independent sign bits.')
p('The decoder reassembles the sign bits followed by the amplitude bits, carries partial bytes across frame boundaries, and reverses the role-selected scrambler. This ideal symbol-domain inverse recovers the original source bytes in the continuous tests. It assumes that the six octets, bank configuration, frame alignment and initial parity are already known. It does not implement an analogue equalizer, acquisition procedure or the recovered client receiver.')

page();hd('12 Symmetric role and capability selection')
sub('12 1 Roles and compatible endpoints')
p('Vendor management definitions identify x2 symmetric as a distinct role: both endpoints send and receive at the same x2 speed. The HiPer DSP pairing diagnostic permits either a server with a client, or two symmetric endpoints. An asymmetric server setting alone therefore does not establish compatibility between two digital modems.')
p('Symmetric operation requires digitally attached endpoints and a channel that preserves the required sample alphabet in both directions. A conventional analogue Courier has a local codec and DAA; its shared 64000 result strings do not establish symmetric support. The I-modem exposes server and symmetric controls in S58. Total Control equipment exposes corresponding disable controls in S76. These register numbers and values are product specific.')
table('Table 13 — I-modem S58 controls',['Value','Meaning when set','Symmetric significance'],[('1','Disable x2','Reject x2 operation'),('2','Disable asymmetric server mode','Does not itself disable symmetric mode'),('4','Force x2 A-law mode','Select the advertised law option'),('8','Disable symmetric mode','Remove symmetric capability'),('16','Enable -6 dBm constellation','Optional advertised constellation'),('32','Disable V.90','Keep the tested call on x2')],[18,74,74])
p('Values 1, 2 and 8 are disable controls, as confirmed by the decoded help tokens and capability builder. For the recorded I-modem test, S58 = 48 sets values 16 and 32, leaving x2, server and symmetric operation enabled. S58 = 34 leaves symmetric operation enabled while disabling asymmetric server mode and V.90; the earlier restricted-DTE tests of that setting reached V.34, not symmetric x2.')
sub('12 2 Capability advertisement and mode selection')
p('Setting the server-disable control clears capability-word bit 12; setting the symmetric-disable control clears bit 11. The constellation option sets bit 10. The capability word is transferred to the transmit INFO0 work area. This establishes the control-to-advertisement path, but does not recover the complete peer decision that selects symmetric operation.')
p('The server decides how to treat the peer from the two exchanged capability words before it arms the marker receiver in clause 5.2. In INFO0 bit numbers it requires the peer to advertise high-carrier 3200 symbol operation, bit 18. It then compares the asymmetry most significant bit, bit 23, and the CME bit, bit 24. If both words have bit 23 set, it leaves the marker path and enters the common mode initializer with a locally written mode word, using the role flag to split the two ends. The initializer installs the digital startup source, a repeated sequence of 1,747 constant words, seven zero words and 128 ascending and descending pairs. The answering end runs that source at once. The originating end keeps its idle transmit hook, which writes one constant idle word per call, and starts the source only after its receive state machine has acquired the answering end source cycle. That machine is a word receiver: it needs seven consecutive run words, then seven low-valued zero words, then verifies the 128 ramp pairs one word at a time, the first of each pair against a running count and the second against its complement from 255. Both ends run the same receiver on the peer source. It tolerates a received word that differs from the expected word only in the lowest bit, counts such words per symbol phase in a six-bit map, and logs unexpected words for the host; any larger difference in the pair phase restarts acquisition from the run words. The receiver has no timeout of its own. In the recorded call the originating end completed it about ten million DSP instructions after starting to listen. A trace of both servers in the recorded symmetric call executes this branch and not the marker path. Otherwise the two words must differ in bit 24, which separates a server from a client, and the peer is treated as a client. If the words are equal in bit 24 the x2 selection is dropped. Both server images contain this test.')
p('When acquisition completes, each end sends a short repeated frame in the same word stream and receives the peer frame. Words carry six data bits and have the lowest bit set; two start words precede a body of five words and four words carrying the inverted CRC-16, which the receiver checks against the standard residue. The body carries a six-bit map of symbol phases with errors seen by the sender, a flag word and a six-bit mask. The receiver forms the union of the two error maps and the intersection of the two masks, then both ends switch to the data-mode handlers and notify the host. In the recorded symmetric call both frames carry an empty map and the same mask. The six symbol phases give a per-position test of the lowest bit of the source words; the natural cause is robbed-bit signalling, which the firmware does not state.')
p('After the merge each end derives its rate from the intersected mask. If the 64000 bit survived, which requires that the peer reported an empty error map, it reports 64000 to the host; otherwise, if the lower bit survived, it reports 56000, using the same report with equal values of sixteen and fourteen in units of 4000 bit/s. The recorded call reports 64000. In a controlled test that flipped the lowest bit of every sixth octet of the startup source on the bearer, on either of two phases, both ends reported 56000 and connected at 56000 with the payloads delivered; flipping the next bit instead abandoned x2 and fell back to V.34. A low-bit error on a single symbol phase is therefore tolerated, recorded, reported to the peer and lowers the rate to 56000.')
p('Capability advertisement, enabled-rate mask and datapump mode are separate parameters. The actual engine mode comes from call descriptors, through a different command path. A capability bit does not by itself identify the active engine branch. The fixed digital-call controls in S67 also operate separately from S58 symmetric capability. Annex A records the corrected command identities and source references.')

page();hd('13 Symmetric bearer and sample transforms')
sub('13 1 Digital rate and word width')
p('At an 8000-word/s bearer cadence, eight information bits per word give 64000 bit/s in each direction; seven give 56000 bit/s. The recovered I-modem digital width routine installs matching transmit and receive widths and masks. Mode bit zero clear selects eight bits and mask FF hexadecimal; set selects seven bits and mask 7F hexadecimal. The fixed digital-call rate control in S67 reaches this mode through the call-descriptor command path.')
p('Digital 56000 shall be distinguished from analogue downstream x2 56000. The former is seven bits per digital bearer word. The latter is a six-symbol allocation of 42 information bits over 8000 samples/s, using mapped codewords and the sign machinery in clauses 10 and 11. Equal printed rates do not imply identical coding.')
p('The width and sample routines are verified components of the server and digital-mode program. A live Ie030002 pair trace confirms the eight-bit digital callbacks, GPC scrambling and octet reversal during the successful symmetric 64000 call. The six-symbol Quad downstream mapper shall therefore not be assigned to symmetric 64000 simply by extrapolating its rate table.')
sub('13 2 Transmit and receive processing')
p('The recovered transmit callback obtains a source word, masks it to the selected width, optionally scrambles it, optionally reverses the octet and writes the sample. The receive callback records the incoming sample, reverses the octet when selected, masks it and optionally descrambles it before calling the sink. Reversal changes bit order within a word; it does not change the number of information bits.')
p('For the directly called scrambler and descrambler entries, the feedback recurrence is 1 + x^-18 + x^-23, known as GPC. If u[n] is the input bit and s[n] the transmitted scrambled bit, s[n] = u[n] XOR s[n-18] XOR s[n-23]. Descrambling uses the received scrambled history in the same XOR relation to recover u[n]. Execution checks cover the updated history as well as the resulting words. The successful Ie030002 64000 pair also verifies activation of both transforms and zero-history initialization before the data phase.')
p('Transmit and receive histories are separate and continue across callback invocations. The component tests preload a source word and disable source and sink dispatch. The separate live-call trace samples original callbacks with source and sink dispatch running; complete queue semantics and symmetric acquisition remain open. An additional width-aware training source packs repeated 7E hexadecimal into a bit reservoir; 256 consecutive words at each of the seven-bit and eight-bit widths match the original instructions.')
sub('13 3 Channel preservation')
p('The successful pair exchanges PCMU bearer octets directly between two native I-modem datapumps. Its result applies to that byte-exact digital path. Linear-audio conversion, companding-law changes, resampling, lossy transport or robbed-bit signalling can alter the available alphabet and require separate qualification. An 8000-sample/s audio path alone does not establish eight-bit transparency.')

page();hd('14 Symmetric connection evidence and limits')
sub('14 1 Recorded full-rate pair')
p('Two original Ie030002 supervisors and native C51 datapumps establish CONNECT 64000/ARQ/x2/LAPM over a direct PCMU B-channel. Both use S54 = 0, S58 = 48, the saved National ISDN-1 profile, a 230400-bit/s DTE and an unrestricted PCM rate mask.')
table('Table 14 — Recorded pair outcomes',['Configuration','Carrier at both ends','Bidirectional data'],[(PAIR_CONTROL['settings'],'64000/ARQ/x2/LAPM','No markers delivered; carrier lost'),(PAIR['settings'],'64000/ARQ/x2/LAPM','Both distinct markers delivered exactly')],[42,58,66])
p('The successful run records 252 complete 100 ms bearer frames per endpoint, zero PCM underruns and no CPU or DSP error. The caller receives ANSWER-X2-S58-48 and the answerer receives CALLER-X2-S58-48. Original firmware produces carrier and DTE output; the harness injects neither.')
p('This emulator test verifies carrier and short bidirectional payload delivery. Sustained throughput, hardware interoperability and public-network operation remain untested. The S58 = 32 control reaches carrier but loses it without delivering markers; the test does not establish S58 = 48 as a universal peer requirement.')
sub('14 2 DTE and rate eligibility')
p('The originating supervisor rejects x2 below the 38400-bit/s DTE entry. It restricts the PCM rate mask to 0003 through the 57600 entry and to 0FFF at 115200; 230400 keeps the full mask. These are firmware-profile limits. Early 9600-bit/s DTE tests reached V.34.')
sub('14 3 Live full rate scrambling evidence')
p('A repeat pair trace uses the original Ie030002 transmit callback E97E and receive callback E992. The caller engine mode is 0310 hexadecimal and the answerer mode is 0210; both set scrambling mask 0200. Both transmit widths are eight, with mask FF, and FFD9 bit 15 enables octet reversal. The verified digital chain therefore assembles eight source bits, applies GPC scrambling, reverses the octet and writes one bearer word. These source bits include the modem link framing; raw terminal octets are not sent unchanged onto the bearer.')
p('The live trace captures zero transmit and receive histories at E908 twice per endpoint: during initial mode setup and again after the data callbacks are selected, before CONNECT. The width initializer E8E1 clears transmit cells 03D8 and 03D9 and receive cells 031E and 031F. After CONNECT, 12224 transmit input snapshots provide 12033 consecutive within-window GPC history transitions, all matching the recovered recurrence. The windows are samples of the running call, not a complete bearer recording. Both distinct terminal markers arrive and both receivers report zero underruns.')
sub('14 4 Remaining protocol reconstruction')
p('The server side of peer role selection from INFO0 is described in clause 12 2. The client side, startup ordering after marker acceptance, rate acknowledgement, alignment, complete queue semantics and retrain or fallback behavior remain open. The component lift uses IM020104; the live trace uses Ie030002. Their instructions have not been shown identical.')
p('Total Control documentation names V.90 all-digital as DDPCM with separate controls and reported modulation. That metadata does not establish an I-modem implementation. This draft specifies the supported x2 evidence.')

page();hd('15 Rates and information carried per sample')
sub('15 1 Rate families')
p('A modem rate describes information bits carried per second, not the size of the stored sample alone. Every six-symbol PCM frame still emits six octets at an 8000-sample/s cadence. Lower information rates use fewer selectable combinations of those octets. In the recovered digital callback, by contrast, the selected width directly specifies seven or eight information bits per bearer word. Both paths can report 56000, but their mappings differ.')
table('Table 15 — Complete x2 reported rate ladder',['Reported bit/s','K per six samples','Rate interpretation'],[(rate,k,'Six-symbol PCM allocation') for rate,k in [(33333,25),(37333,28),(41333,31),(42666,32),(44000,33),(45333,34),(46666,35),(48000,36),(49333,37),(50666,38),(52000,39),(53333,40),(54666,41),(56000,42),(57333,43)]]+[(64000,48,'Digital endpoint; eight bits per word')],[37,49,80])
p('For the six-symbol interpretation, R = K × 8000 ÷ 6 bit/s. Printed rates truncate fractional values: 33333 denotes 33333⅓ and 42666 denotes 42666⅔. The x2 ladder skips K = 26, 27, 29 and 30; it is not every integer allocation between its lowest and highest entries. Rates below 33333 belong to another modulation or digital rate-adaptation mode in the inspected product, not to this x2 ladder.')
p('Table 15 records the firmware result ladder and its numerical six-sample correspondence. It does not establish a symmetric call at every listed rate, nor a wire encoding for those rates. K = 48 at 64000 is an arithmetic comparison, not evidence that the lower-rate constellation mapper produces that digital endpoint.')

page();hd('16 Lower rate PCM mapping and scrambling')
sub('16 1 Information allocation')
p('The recovered Quad PCM frame consumes K = B + MD scrambled information bits: MD bits for independent signs, followed by B bits for amplitude choices. MD can be zero through six. The six minus MD remaining signs carry shaping choices rather than additional source bits. The nominal information rate for a given allocation is (B + MD) × 8000 ÷ 6. The sample cadence remains 8000/s.')
p('A reduction in B restricts the amplitude-choice integer and the required bank capacity. A reduction in MD leaves more signs free for disparity shaping. Neither operation amounts to taking the low five or six bits of each input byte and sending them directly. Byte boundaries can cross frames; scrambler history and differential-sign parity continue across those boundaries.')
table('Table 16 — Executed Quad builder profiles',['Local index','B','Six bank sizes in emission order','Rate if MD is 6'],[(x['rate_index'],x['amplitude_bits'],', '.join(map(str,x['sizes'])),(x['amplitude_bits']+6)*8000//6) for x in PAYLOAD['negotiated_profiles'] if x['flags']==0],[24,14,87,41])
p('Indices 1 through 15 are executed, seeded mode-zero builder contexts with DSP product scaling mode SPM 1 and matching profiles for both tested format flags. Index 15 supplies B = 37 and uniquely decodable banks. The right-hand column is calculated with MD = 6; it is not a captured rate agreement. A local builder index shall not be used directly as a transmitted rate code.')
sub('16 2 Worked allocations')
p('Local index 8 supplies B = 30 and six banks of 32 entries. With MD = 6, the frame carries 36 information bits and corresponds to 48000 bit/s. With MD = 3, it carries 33 bits and corresponds arithmetically to 44000 bit/s, with three signs reserved for shaping. With MD = 0 it corresponds to 40000 bit/s, which is absent from the x2 result ladder. These examples show why component arithmetic alone does not establish a negotiable rate.')

pp=d.add_heading('16 3 Verified 57333 profile',2);pp.paragraph_format.page_break_before=True
p('Local index 15 with MD = 6 consumes 43 bits per six samples: six independent sign bits first, then 37 amplitude bits. At 8000 samples/s this is 57333⅓ bit/s. All six signs carry information through differential parity; no signs remain free for disparity shaping. The source bits are scrambled before grouping, using the same recovered role-selected GPC or GPA recurrences as the other Quad allocations.')
p('For the default mode-zero record, emission-order bank sizes are 82, 70, 70, 70, 70, 70. Their product is 137817400000, exceeding 2^37 = 137438953472. The mapper takes successive remainders and quotients of the 37-bit integer in those radices. Each bank digit selects one uniquely identified magnitude codeword. The six sign bits toggle the sign of those selected codewords. Only the first 2^37 mixed-radix combinations carry amplitude payload.')
table('Table 16 1 — Verified rate index 15 bank variants',['Mode','Flag bit 2','Nonzero positions','Banks in emission order'],[(0,0,0,'82, 70, 70, 70, 70, 70'),(0,0,1,'45, 79, 79, 79, 79, 79'),(0,1,0,'72, 72, 72, 72, 72, 72'),(0,1,1,'48, 78, 78, 78, 78, 78'),(0,1,2,'49, 49, 87, 87, 87, 87'),(1,0,0,'72, 72, 72, 72, 72, 72'),(1,1,0,'72, 72, 72, 72, 72, 72'),(1,1,1,'42, 80, 80, 80, 80, 80'),(1,1,2,'46, 46, 90, 90, 90, 90')],[18,24,37,87])
p('The probe sets nonzero position nibbles to two at the first one or two positions; their ordering is part of the seeded record. Mode two shares the tested mode-zero bank sizes. Both flag-bit-zero states pass. Other forced record combinations do not supply enough capacity at index 15; their descriptor rows do not all extend to this index. This table establishes constructed profiles, not which record a peer selects during negotiation.')
p('The builder requires SPM 1 for its multiply-and-accumulate scaling. Earlier SPM 0 probes produced duplicate entries or failed to return and are superseded. Corrected probes validate 28 of 36 candidate contexts with 1792 exact-symbol round trips, including zero and maximal 43-bit groups. Continuous byte-stream tests also recover the original bytes at index 15 through the unmodified source appender and six-sample dispatcher. An established 57333 call and analogue client acquisition remain unverified.')

page();hd('17 Data transforms and lower rate symmetric limits')
sub('17 1 Lower rate transmit and receive chain')
p('For the verified Quad PCM core, the transmit order is source bits, role-selected scrambling, bit buffering, sign and amplitude grouping, mixed-radix amplitude selection, differential signs and disparity shaping, then output formatting. Scrambling occurs before mapping. The source routine calls its scrambler as part of every append in the verified branch; it is not an optional post-mapping octet XOR.')
p('The role flag selects the recovered GPC recurrence 1 + x^-18 + x^-23 or GPA recurrence 1 + x^-5 + x^-23. Continuous tests cover both role values. The feedback history is the transmitted scrambled bit stream; the receiver uses received scrambled history for the inverse. The modem-role assignment of every complete call branch and its scrambler reset timing remain separate reconstruction work.')
p('After undoing output formatting, an ideal receiver recovers bank digits and reference-relative signs, reverses mixed-radix selection, recovers the independent bits from differential parity, reassembles the sign and amplitude groups into a continuous bit stream, then descrambles that stream into source bytes. Analogue acquisition and equalization are needed before these symbol decisions. The ideal inverse used in the tests assumes exact octets and known alignment.')
sub('17 2 Direct digital transforms')
p('The I-modem digital callback masks each assembled word, conditionally scrambles it with GPC, conditionally reverses its octet and writes it. Engine mode mask 0200 hexadecimal enables scrambling. A separate flag selects reversal. Reception reverses the order of those transforms: optional reversal, width mask and optional GPC descrambling. Eight-bit mode gives 64000 bit/s; seven-bit mode packs a continuous source stream into seven-bit words and gives 56000 bit/s. It does not drop every eighth source bit.')
p('No five-bit, six-bit or fractional-width selection has been recovered in that width initializer. Lower x2 rates therefore shall not be described as direct words of progressively fewer bits based on this routine. Likewise, optional scrambling in this callback shall not be confused with the mandatory source scrambler in the tested Quad mapping branch. The successful 64000 symmetric pair has now been traced: eight-bit digital callbacks, GPC scrambling and octet reversal are active on both ends. Seven-bit symmetric activation and lower-rate call profiles still require their own live traces.')
sub('17 3 What lower rate symmetric operation establishes')
p('Vendor symmetric mode requires the same x2 rate in both directions. The saved successful test establishes 64000/64000. No saved full-call test used here establishes 56000/56000 or a lower symmetric rate, and the recovered lower-rate Quad mapper has not been tied to a complete symmetric call. Digital seven-bit operation is established as a component and control path, not as proof of symmetric x2 at 56000.')
p('For a complete lower-rate symmetric specification, a call must connect the negotiated directional rates to the selected transmit and receive callbacks, word width or six-symbol allocation, bank records, scrambler flags and initial states. Bidirectional payload must then be recovered at that rate. V.34 fallback and the I-modem V.110, V.120 or X.75 rate-adaptation paths use different coding and shall not be counted as lower-rate x2 merely because they share a B-channel or a result speed.')

page();hd('18 PCM record selection and data handoff')
sub('18 1 Received parameters and rate selection')
p('Original Quad instructions now execute the PCM record receiver, rate resolver, bank constructor and output scheduler together. The harness supplies decoded input bits and local call state; it does not inject the received working record, selected index or final banks. This establishes the server consumer of a chosen record. How analogue client measurements produce that record, and how a complete x2 call selects this branch, remain open.')
p('In the tested receiver branch, at least seventeen one bits followed by zero introduce four 16-bit words. Each word is sent least significant bit first and followed by a zero separator. Sixteen least significant bit first CRC bits follow. The CRC starts at FFFF, uses reflected polynomial 8408 and has no final XOR. Separators are excluded. Matching CRCs commit the words to working parameters; mismatches leave those working parameters unchanged. This is the four-word PCM record receiver, not the unresolved short proprietary directional-announcement receiver.')
p('For the tested PCM transmit direction, let L be the peer ceiling from bits 2 through 5 of the first received word, and M the local fifteen-bit allowed-rate mask. The selected local index is bit_length(M AND (2^L minus 1)). Bit zero permits local index one, through bit fourteen permitting index fifteen. The bank builder uses this index minus one. A zero eligible mask returns index zero; its refusal or fallback handling remains outside the integrated success tests.')
table('Table 18 — Rate selection under a peer ceiling of fifteen',['Local mask','Selected index','B','Rate with MD six'],[('7FFF',15,37,57333),('3FFF',14,36,56000),('0081',8,30,48000)],[40,38,18,70])
p('Mode, independent sign count and position choices are consumed from the accepted record separately. Rate selection restricts the amplitude allocation; it does not search channel measurements for the best constellation. Client rate intersection and a separate variable-length position-report constructor are verified in clause 19. Their complete scheduling and connection to this four-word branch remain open.')
sub('18 2 Scheduler and later source activation')
p('The original scheduler first emits six startup samples, then resolves the rate and builds all six banks. It installs the six-symbol data mapper for a 4080-sample phase. After that countdown, a later transition enables the payload-source gate, sets its local format-state flag, queues notification word 0003 and installs the ordinary payload-source callback. The host meaning of the notification and complete external queue delivery are not established here. Mapper installation and payload-source activation are distinct transitions.')
p('Verification covers 1249 mask/ceiling comparisons, 128 accepted records, 256 corrupt-record rejections and 40 integrated record-to-rate/bank/data contexts. The contexts include all fifteen indices, output variants, rate-15 bank variants and local-mask reductions. Across 7680 continuously dispatched samples, 1280 exact-symbol frame inverses match the consumed scrambled bits. One 57333 context also completes the full countdown through source activation. Ring input is supplied through the original scrambler/appender; analogue demodulation and external payload queues are outside this test.')

page();hd('19 Client measurement record construction')
sub('19 1 Rate mask intersection')
p('The original 3453B 2.1.1 firmware predates V.90. It executes the same rate-mask intersection, position grouping and variable-length serialization as 3453C 2.3.33. These procedures therefore belong to retained x2-era client machinery. The tests seed measurement matrices and initial headers; they do not reconstruct analogue acquisition or prove automatic call-state selection.')
p('The rate selector intersects a measurement mask, a host allowed-rate mask and a low-bit ceiling mask. Both masks are 32 bits. For the verified limits 1 through 31, the result is the bit length of the surviving mask. A zero intersection returns index zero. The first record word preserves its control fields and receives that selected index shifted by two or three bits, according to the local role flag. This executes in 496 contexts per firmware, covering both role states, eight local offsets and randomized sparse masks.')
p('The ceiling is calculated from a local limit and offset: limit equals the stored limit plus offset minus twenty. The physical meaning of that offset remains unresolved. The test does not assign nominal line rates to all thirty-one possible mask positions. After selection, the continuation receives selected index minus offset plus twenty. A zero initial stored limit returns before intersection.')
sub('19 2 Position groups and the report body')
p('The constructor compares two measurement matrices, each with six positions of eight 16-bit words. It groups matching pairs of position blocks and assigns group numbers in first occurrence order. The first five header words are preserved. Two control words encode the six group numbers as four-bit values, with a flag indicating whether the complete matrices differ.')
code('word[5] = group[0] | group[1]<<4 | group[2]<<8 | group[3]<<12\nword[6] = group[4] | group[5]<<4 | different<<8\nword_count = 7 + 8 * group_count * (1 + different)')
p('The first matrix contributes one eight-word representative block per group, in group order. When the matrices differ, the second matrix contributes the same number of representative blocks in that order. The body contains 15 through 103 words. The flag selects a second bitmap set; it is not the independent sign count used by the short-record mapper.')
table('Table 19 — Constructed position report examples',['Groups','Position sequence','Equal matrices words','Different matrices words'],[(1,'0 0 0 0 0 0',15,23),(2,'0 1 0 1 0 1',23,39),(6,'0 1 2 3 4 5',55,103)],[20,54,46,46])
p('For six distinct positions, the control words are 3210 and 0054, or 3210 and 0154 with the second set. For alternating groups zero and one, they are 1010 and 0010, or 1010 and 0110. An independent reconstruction matches the complete native-constructed body in 76 contexts per firmware, including all group counts with equal and different matrices.')

page();hd('20 Client record framing and verification')
sub('20 1 Original serializer execution')
p('Each native-constructed body and its returned word count feed the original transmit initializer. That initializer installs the source pointer, length, seventeen-bit preamble and serializer callbacks. All 152 constructed reports then match the independent framing and CRC reconstruction through the original serializer. The harness enters the initializer; the call-state transition that selects it remains open.')
p('The serializer emits seventeen one bits and a zero, then each 16-bit body word least significant bit first with a zero separator. Sixteen least significant bit first CRC bits follow. CRC starts at FFFF, uses reflected polynomial 8408 and has no final XOR. The separators are excluded. A subsequent callback emits a zero tail. This is the same framing verified for the short server record in clause 18.')
p('The pre-V.90 serializer separately passes 96 seeded bodies of one, two, four, six, seven and nine words. Sixty-four four-word bodies from the later client serializer pass the original Quad receiver and commit all four words unchanged. That proves framing compatibility; it does not establish that the variable-length client body is the short four-word record selected by that server branch. Its five preserved header fields, call-state scheduling and corresponding peer receiver still require tracing.')
sub('20 2 Diagnostic report and DSP timing')
p('A different routine summarizes six bitmap windows and counts those with fewer than twenty set bits. Its output belongs to the host diagnostic report path. It is not the peer-negotiation body described above. Its packing matches original instructions for 1024 contexts across the two client versions. This removes the diagnostic summarizer as a candidate for the missing peer producer.')
p('The threshold routine exposed an emulator condition-timing error. TI specifies that XC samples its accumulator and status conditions one full cycle before execution. A single-cycle predecessor cannot replace the sampled condition. The corrected core preserves that sample, including delayed-branch slots. Six focused regressions, the full repository suite and a fresh 64000/64000 symmetric call pass after the correction. The call confirms bidirectional marker delivery, eight-bit GPC scrambling, octet reversal and two zero-history resets per endpoint.')
p('The remaining measurement boundary is now narrower: received analogue samples must be traced into the two position matrices and rate mask. Complete negotiation also requires automatic report scheduling, header interpretation, the corresponding peer receiver, frame alignment and the analogue payload decoder. These results shall not be described as a complete asymmetric x2 call.')

page();hd('Annex A Firmware evidence and reproduction')
annex_start=len(d.paragraphs)
p('This annex is informative. It retains implementation detail for traceability without making addresses part of the protocol description. The manually reconstructed C is not vendor source.')
table('Table A 1 — Firmware profiles',['Profile','Image','Role'],[('Client','3453C version 2.3.33 XMF','Retained x2 setup, low overlay and PCM training'),('Original server','IM020104.NAC','Capability packing, startup source and sample transforms'),('Later server','QF060003.NAC','PCM preparation and six-symbol payload core')],[30,59,77])
p('Evidence directories under artifacts are 3453c-x2-decomp-20261004, x2-server-decomp-20261004, x2-mapper-negotiation-20261004 and x2-payload-mapper-20261004. Each preserves the reconstruction and comparison evidence for its profile.')
table('Table A 2 — Comparison coverage',['Group','Count','Qualification'],[('Client','1,793','Original mapped client instructions'),('Original server','6,474','Original mapped server instructions'),('Quad helpers','88','Corrected stock-verified source placement'),('Mapper C comparisons','13,504','Transfer, unpacking, count, sizes and bank expansion'),('Startup caller contexts','128','Unmodified constructor and consumers; seeded candidates'),('Overlay source copies','28','Seven overlays across four stock controller RAM banks'),('Client diagnostic packing','1,024','Two original client versions; host report'),('Client rate intersection','992','Both roles and limits 1 through 31'),('Position report bodies','152','Complete bodies and original serializers'),('Serializer interoperability','64','Original client bits through original server receiver'),('PCM handoff','40','Record acceptance through selected banks and continuous mapping'),('PCM CRC','384','128 accepted bodies and 256 rejected corrupt bodies'),('Rate selection','1,249','One-hot and sparse masks with peer ceilings'),('Payload core',format(PAYLOAD['total_cases'],','),'Components, 30 builder profiles and continuous output'),('Decoded source bytes',format(PAYLOAD['decoded_source_bytes'],','),'56 streams of 32 frames with an ideal symbol inverse')],[49,23,94])
d.add_page_break()
p('Mapper entries are AB06 for received-record transfer, C870 for unpacking, C6E5 for the six-position count, C6F4 for size distribution and C92A for descriptor expansion. The first candidate source is 0A60 and the second is 0880; expanded banks begin at E8F4 with a stride of 0080. The codeword constructor is C9BF; the integrated startup caller begins at C840.')
p('Run tools/recover_3453c_x2.py, tools/recover_x2_server.py, tools/recover_x2_mapper.py and tools/recover_x2_payload.py with the repository Python environment. The scripts compile manual C lifts and compare their effects with original DSP instructions. Run tools/verify_quad_pcm_placement.py for the independent stock overlay-copy check.')
p('The impairment test is tools/x2_source_impairment.py with artifacts/x2-source-impairment-20261004/verification.json. The marker receiver is documented at the end of docs/x2-v90-protocol-selection.md; tools/verify_x2_marker_receiver.py runs the original QF060003 parse from 97B5 and writes artifacts/x2-marker-receiver-20261004/verification.json. The arming site is 9791; the IM020104 counterpart is 948A.')
p('The payload entries are B2BA for source append, C5DF for amplitude selection, C642 for signs and C544 for frame output. Builder entry C862 receives a preselected rate index. The tested branch has 039F bit 7 and FFD9 bit 12 clear. Profiles use default position choices, flags zero and one, mode zero for rate indices 1 through 15, and SPM 1. Continuous streams cover indices 10 and 15. tools/probe_x2_57333_profile.py additionally checks the rate-15 bank variants; x2-57333-profile-20261004 preserves the candidate scan and bank snapshots. verification.json and example.json preserve the results. The payload aggregate counts component cases, sample steps and streams; it does not represent independent connection trials.')
p('The protocol history in docs/x2-v90-protocol-selection.md includes the preamble-detector correction. Field terminology follows ITU-T V.34 Table 14, available at https://www.itu.int/rec/T-REC-V.34-199610-S/en. V.90 context is at https://handle.itu.int/11.1002/1000/4493.')
revision=p('Draft 0.21 reproduces the 56000 decision with a controlled low-bit impairment of the startup source. Draft 0.20 decodes the data-mode hook families and the rate decision after the capability exchange. Draft 0.19 decodes the in-band capability frame. Draft 0.18 decodes the receiver mismatch handling. Draft 0.17 decodes the startup source receiver that ends the wait. Draft 0.16 decodes the originating-end idle stub and the wait that ends it. Draft 0.15 traces the symmetric startup branch. Draft 0.14 specifies the server peer-role test on the exchanged INFO0 words. Draft 0.13 traces the server after marker acceptance. Draft 0.12 identifies the server receiver for the seven-bit marker and verifies its field parse. Draft 0.11 resolves the 3453C capability route: the transmitted INFO0 word is the plain tag 51 word and the tag 70 word is never read. Draft 0.10 adds pre-V.90 and later client rate selection, position grouping, variable-length body construction and original serialization. It distinguishes the host diagnostic report from peer records and records the XC timing correction and successful symmetric regression. Draft 0.9 executes the four-word PCM record receiver through CRC acceptance, rate-mask selection, bank construction, mapped output and later payload-source activation. The client measurement-to-record producer and complete call-state selection remain open. Draft 0.8 verified 57333 profiles and corrected builder product scaling to SPM 1. Draft 0.7 confirmed active GPC scrambling and pre-data resets in the symmetric 64000 pair. Analogue client decoding, alternate companding output and complete peer negotiation remain open.')
revision.paragraph_format.page_break_before=False
p('Client record evidence is documented in docs/x2-client-record-production.md and artifacts/x2-client-record-20261004/packer-verification.json. Run tools/trace_x2_client_record.py. Original rate entries are E773 and 6818; position constructors F16B and 720A; serializers ADE2 and 2E3A; transmit initializers C5E8 and 4650. The pre-V.90 source is 3453B 2.1.1. The diagnostic packers are DE1D and 5EC3. The post-correction call is artifacts/x2-xc-pair-20261004, checked by tools/verify_x2_scrambler_trace.py. TI SPRU056D section 4.5.6 and XC page 6-278 establish the condition sampling rule.')
p('The PCM handoff reconstruction is documented in docs/x2-rate-and-data-handoff.md. tools/trace_x2_rate_handoff.py reproduces the checks; artifacts/x2-rate-handoff-20261004 contains verification.json, 57333-trace.json and handoff.asm. The tested mode is 039F = 8040 with bit 7 clear and SPM 1. Original entries are AAA4/A9EA for record reception, AB06/AB24 for transfer, AA45 for script selection, AC34 for rate resolution, C52A/C85E/C862 for preparation, C544 for mapping and C52E for source activation. Script C7E7 supplies six startup samples and 0FF0 mapped samples. Source callback 84FB is installed at activation. The verified selection formula applies to direction selector one; other directions are separate work.')
d.add_page_break()
p('Symmetric role and control evidence is collected in docs/x2-symmetric-and-all-digital.md, especially its later command-table, bit-number and tokenized-help corrections. Vendor sources are HDM.MIB in docs/x2/tcmw551.zip, the HiPer DSP reference 24187300.PDF and the NETServer RADIUS dictionary in docs/x2/ne050303.zip. The management controls are S76.0 client-disable, S76.1 server-disable and S76.2 symmetric-disable; the dictionary reports x2symmetric as modulation 30. These identifiers are management metadata, not wire fields.')
p('In IM020104, host tags 70 and 71 reach DSP entries 91A1 and 91AE, storing capability and rate words at FFDB and FFDA. Mode tags 5C and 5D reach E11E and E11A. Digital width setup is E5E7; sample callbacks are E65F and E67B; the directly called GPC entries are 8FAA and 8FE1; octet reversal is E7E7. The corrected dispatch-table base is 882B. Tag 70 is not the engine-mode command.')
p('The full-call evidence is artifacts/imodem-pair-x2-full-rate-high-power-20261002/verification.json; the carrier-only control is artifacts/imodem-pair-x2-full-rate-v8-server-20261002/verification.json. Both successful endpoints send 0070:3DFF and 0071:FFFF. Setup, DTE restrictions and the reproduction command are documented in docs/imodem-x2-pair.md. The paired harness is tools/probe_imodem_pair.py; its --check-x2 gate requires x2 in the firmware CONNECT result. Marker checks independently establish data delivery.')
p('The live scrambler evidence is artifacts/x2-scrambler-call-reset-20261004/verification.json and the associated originate.json and answer.json traces. tools/probe_imodem_pair.py --trace-digital-path records mode writes and read-only instruction-boundary snapshots; tools/verify_x2_scrambler_trace.py checks widths, flags, callback addresses, zero histories and the GPC recurrence. These addresses apply to Ie030002, not to the earlier IM020104 lift. Initial connection resets are verified; retrain and lower-rate resets remain open.')
p('The Quad B table is program C9E0 through C9EE: 19, 22, 25, then 26 through 37. C862 subtracts one from the local index before looking up this table. MD is read separately from bits 8 through 10 of the working position record. Every row of Table 16 is generated from an executed builder profile in the saved payload verification. Continuous stream checks use B = 32 and B = 37 with all MD values, both role flags and both tested output-format states.')

for pp in d.paragraphs[annex_start:]:
 if pp.style.name=='Normal':
  pp.paragraph_format.space_after=Pt(4)
  pp.paragraph_format.keep_together=True
  for rr in pp.runs:rr.font.size=Pt(10)
d.core_properties.title='x2 Modem Technical Specification'
d.core_properties.subject='Negotiation downstream mapping and symmetric operation firmware reconstruction'
d.core_properties.author='Courier emu project'
d.save(OUT/'x2-technical-specification.docx')
print(OUT/'x2-technical-specification.docx')
